' cabbage': 90
' hanamaki baozi': 61
French beans: 95
almond: 16
apple: 24
apricot: 26
asparagus: 84
avocado: 27
bamboo shoots: 85
banana: 28
bean sprouts: 91
biscuit: 4
blueberry: 31
bread: 57
broccoli: 86
cake: 9
candy: 0
carrot: 83
cashew: 18
cauliflower: 71
celery stick: 87
cheese butter: 8
cherry: 30
chicken duck: 47
chocolate: 3
cilantro mint: 88
coffee: 12
corn: 58
crab: 52
cucumber: 81
date: 25
dried cranberries: 19
egg: 23
egg tart: 1
eggplant: 68
enoki mushroom: 98
fig: 38
fish: 53
french fries: 2
fried meat: 49
garlic: 70
ginger: 77
grape: 40
green beans: 94
hamburg: 59
ice cream: 7
juice: 13
kelp: 73
king oyster mushroom: 96
kiwi: 41
lamb: 50
lemon: 36
lettuce: 79
mango: 33
melon: 42
milk: 14
milkshake: 11
noodles: 64
okra: 78
olives: 34
onion: 92
orange: 43
other ingredients: 102
oyster mushroom: 99
pasta: 63
peach: 35
peanut: 22
pear: 37
pepper: 93
pie: 66
pineapple: 39
pizza: 60
popcorn: 5
pork: 46
potato: 69
pudding: 6
pumpkin: 80
rape: 76
raspberry: 32
red beans: 17
rice: 65
salad: 101
sauce: 51
sausage: 48
seaweed: 74
shellfish: 54
shiitake: 97
shrimp: 55
snow peas: 89
soup: 56
soy: 20
spring onion: 75
steak: 45
strawberry: 29
tea: 15
tofu: 67
tomato: 72
walnut: 21
watermelon: 44
white button mushroom: 100
white radish: 82
wine: 10
wonton dumplings: 62
ketchup: 103
chilli-paste: 104